name: Test Just Curl YAML

on:
  pull_request:
    branches: [ pre_main ]
jobs:
  curl:
    runs-on: ubuntu-latest
    steps:
    - name: post-show-commit
    # trying shorter sha syntax, but why does each run line need its own hyphen??
    - run: echo "This job's commit sha is take55, git_hash=$(git rev-parse --short \"$GITHUB_SHA\")" 
    - run: echo "This job's commit sha is take4 ${{ github.sha }}"
    
    - name: POST CURL test-just-curl.yml
      uses: wei/curl@master
      with:
        # args: https://httpbin.org/get
        args: -X POST http://codechallenge.ents24.com/${{ github.sha }}
    
    - name: show-commit
      run: echo "This job's commit sha is take3, git_hash=$(git rev-parse --short \"$GITHUB_SHA\")" 
    - run: echo "hello"
    
    - name: 'Devops Post Task'
      # cant use uses and runs echo together !
      uses: indiesdev/curl@v1
      id: devops-post
      with:
        url: http://codechallenge.ents24.com/${{ github.sha }}
        method: 'POST'
        accept: 200,201,204, 404
        body: '{ }'
    - name: 'Use response'
      run: echo ${{ steps.devops-post.outputs.response }}
      
    - name: devops-get-task
      run: curl http://codechallenge.ents24.com/${{ github.sha }}
    - run: echo "This job's commit sha is take2 ${{ github.sha }} ."
    - run: echo "git_hash=$(git rev-parse --short '$GITHUB_SHA')" 
    - run: echo "This job's status is ${{ job.status }}." 

# curl --request POST --url https://example.com/ --header 'cache-control: no-cache' --form path=DEPLOY_PATH --form archive=@FILE_PATH --form token=TOKE
